name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF/refs\/tags\//})"
      id: extractBranch

    - name: Build Release APK
      env:
        GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        VERSION: ${{ steps.extractBranch.outputs.tag }}
      run: ./gradlew assembleRelease

    - name: Sign artifact
      id: signArtifact
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release/
        alias: ${{ secrets.ALIAS }}
        signingKeyBase64: ${{ secrets.SIGNING_KEY}}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      id: uploadArtifact
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ${{steps.signArtifact.outputs.signedReleaseFile}}

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GH_ACCESS_TOKEN }}
        automatic_release_tag: ${{ steps.extractBranch.outputs.tag }}
        prerelease: false
        draft: true
        title: ${{ steps.extractBranch.outputs.tag }}
        files: |
          ${{steps.signArtifact.outputs.signedReleaseFile}}
